package com.zc.cris.mybatis.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.id
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.name
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.id
     *
     * @return the value of tb_dept.id
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.id
     *
     * @param id the value for tb_dept.id
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.name
     *
     * @return the value of tb_dept.name
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.name
     *
     * @param name the value for tb_dept.name
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}