package com.zc.cris.mybatis.bean;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.id
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.name
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.gender
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.email
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.dept_id
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.id
     *
     * @return the value of tb_employee.id
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.id
     *
     * @param id the value for tb_employee.id
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.name
     *
     * @return the value of tb_employee.name
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.name
     *
     * @param name the value for tb_employee.name
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.gender
     *
     * @return the value of tb_employee.gender
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.gender
     *
     * @param gender the value for tb_employee.gender
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.email
     *
     * @return the value of tb_employee.email
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.email
     *
     * @param email the value for tb_employee.email
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.dept_id
     *
     * @return the value of tb_employee.dept_id
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.dept_id
     *
     * @param deptId the value for tb_employee.dept_id
     *
     * @mbg.generated Sat Mar 31 09:34:06 CST 2018
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

	@Override
	public String toString() {
		return "Employee [id=" + id + ", name=" + name + ", gender=" + gender + ", email=" + email + ", deptId="
				+ deptId + "]";
	}
    
    
}